using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class ClusterCounter : MonoBehaviour
{
    //Counts points generated by given sphere covers
    public List<SphereCover> layers;

    [SerializeField]
    private int numPoints;
    // Start is called before the first frame update
    void Start()
    {
        Invoke("CountPoints", 1f);
        numPoints = 0;
    }
    void CountPoints()
    {
        foreach(SphereCover layer in layers)
        {
            numPoints += layer.clonedObjectsList.Count;
        }
        Debug.Log("Points in " + name + ": " + numPoints);
    }
}
